export const tableColumnsData = [
  {
    id: 1,
    colName: "Owner",
    styles: "",
    colStyle: "w-24",
    headingStyle: "",
    infoIcon: false,
    dottedIcon: true,
    sortable: true,
    checked: true,
  },
  {
    id: 2,
    colName: "Status",
    styles: "",
    colStyle: "w-36",
    headingStyle: "",
    infoIcon: false,
    dottedIcon: true,
    sortable: true,
    checked: true,
  },
  {
    id: 3,
    colName: "Priority",
    styles: "",
    colStyle: "w-36",
    headingStyle: "",
    infoIcon: false,
    dottedIcon: true,
    sortable: true,
    checked: true,
  },
  {
    id: 4,
    colName: "Type",
    styles: "",
    colStyle: "w-36",
    headingStyle: "",
    infoIcon: false,
    dottedIcon: true,
    sortable: true,
    checked: true,
  },
  {
    id: 5,
    colName: "Estimated SP",
    styles: "",
    colStyle: "w-36",
    headingStyle: "",
    infoIcon: true,
    dottedIcon: true,
    sortable: true,
    checked: true,
  },
  {
    id: 6,
    colName: "Actual SP",
    styles: "",
    colStyle: "w-36",
    headingStyle: "",
    infoIcon: true,
    dottedIcon: true,
    sortable: true,
    checked: true,
  },
  {
    id: 7,
    colName: "Task Due Date",
    styles: "",
    colStyle: "w-36",
    headingStyle: "",
    infoIcon: true,
    dottedIcon: true,
    sortable: true,
    checked: false,
  },
  {
    id: 8,
    colName: "Role",
    styles: "",
    colStyle: "w-36",
    headingStyle: "",
    infoIcon: true,
    dottedIcon: true,
    sortable: true,
    checked: false,
  },
  {
    id: 9,
    colName: "Item ID",
    styles: "",
    colStyle: "w-36",
    headingStyle: "",
    infoIcon: true,
    dottedIcon: true,
    sortable: true,
    checked: false,
  },
];

export const singleTableRow = [
  {
    id: 1,
    colName: "Owner",
    value: null,
    checked: true,
  },
  {
    id: 2,
    colName: "Status",
    value: null,
    checked: true,
  },
  {
    id: 3,
    colName: "Priority",
    value: null,
    checked: true,
  },
  {
    id: 4,
    colName: "Type",
    value: null,
    checked: true,
  },
  {
    id: 5,
    colName: "Estimated SP",
    value: null,
    checked: true,
  },
  {
    id: 6,
    colName: "Actual SP",
    value: null,
    checked: true,
  },
  {
    id: 7,
    colName: "Task Due Date",
    value: null,
    checked: false,
  },
  {
    id: 8,
    colName: "Role",
    value: null,
    checked: false,
  },
  {
    id: 9,
    colName: "Item ID",
    value: null,
    checked: false,
  },
];

export const tableRowsData = [
  [
    {
      rowId: 1,
      id: 0,
      colName: "Task",
      value: "Create new dashboard",
      checked: true,
    },
    {
      rowId: 1,
      id: 1,
      colName: "Owner",
      value: "",
      checked: true,
    },
    {
      rowId: 1,
      id: 2,
      colName: "Status",
      value: "Ready to start",
      styles: "",
      checked: true,
    },
    {
      rowId: 1,
      id: 3,
      colName: "Priority",
      value: "Critical",
      checked: true,
    },
    {
      rowId: 1,
      id: 4,
      colName: "Type",
      value: "Feature",
      checked: true,
    },
    {
      rowId: 1,
      id: 5,
      colName: "Estimated SP",
      value: 1234,
      checked: true,
    },
    {
      rowId: 1,
      id: 6,
      colName: "Actual SP",
      value: 3456,
      checked: true,
    },
    {
      rowId: 1,
      id: 7,
      colName: "Task Due Date",
      value: "16/09/2024",
      checked: false,
    },
    {
      rowId: 1,
      id: 8,
      colName: "Role",
      value: "User",
      checked: false,
    },
    {
      rowId: 1,
      id: 9,
      colName: "Item ID",
      value: "3456",
      checked: false,
    },
  ],
  [
    {
      rowId: 2,
      id: 0,
      colName: "Task",
      value: "Apply styles",
      checked: true,
    },
    {
      rowId: 2,
      id: 1,
      colName: "Owner",
      value: "",
      checked: true,
    },
    {
      rowId: 2,
      id: 2,
      colName: "Status",
      value: "In progress",
      styles: "",
      checked: true,
    },
    {
      rowId: 2,
      id: 3,
      colName: "Priority",
      value: "High",
      checked: true,
    },
    {
      rowId: 2,
      id: 4,
      colName: "Type",
      value: "Test",
      checked: true,
    },
    {
      rowId: 2,
      id: 5,
      colName: "Estimated SP",
      value: 1234,
      checked: true,
    },
    {
      rowId: 2,
      id: 6,
      colName: "Actual SP",
      value: 3456,
      checked: true,
    },
    {
      rowId: 2,
      id: 7,
      colName: "Task Due Date",
      value: "16/09/2024",
      checked: false,
    },
    {
      rowId: 2,
      id: 8,
      colName: "Role",
      value: "Admin",
      checked: false,
    },
    {
      rowId: 2,
      id: 9,
      colName: "Item ID",
      value: "3456",
      checked: false,
    },
  ],
  [
    {
      id: 0,
      colName: "Task",
      value: "Make responsive",
      checked: true,
    },
    {
      id: 1,
      colName: "Owner",
      value: "",
      checked: true,
    },
    {
      id: 2,
      colName: "Status",
      value: "Pending deploy",
      styles: "",
      checked: true,
    },
    {
      id: 3,
      colName: "Priority",
      value: "Low",
      checked: true,
    },
    {
      id: 4,
      colName: "Type",
      value: "",
      checked: true,
    },
    {
      id: 5,
      colName: "Estimated SP",
      value: 1234,
      checked: true,
    },
    {
      id: 6,
      colName: "Actual SP",
      value: 3456,
      checked: true,
    },
    {
      id: 7,
      colName: "Task Due Date",
      value: "16/09/2024",
      checked: false,
    },
    {
      id: 8,
      colName: "Role",
      value: "User",
      checked: false,
    },
    {
      id: 9,
      colName: "Item ID",
      value: 3456,
      checked: false,
    },
  ],
];

export const statusColData = [
  {
    id: 1,
    value: "Ready to start",
    bgColor: "#216EDF",
  },
  {
    id: 2,
    value: "In progress",
    bgColor: "#FDAB3D",
  },
  {
    id: 3,
    value: "Waiting for review",
    bgColor: "#A1E3F6",
  },
  {
    id: 4,
    value: "Pending deploy",
    bgColor: "#7F5347",
  },
  {
    id: 5,
    value: "Done",
    bgColor: "#00C875",
  },
  {
    id: 6,
    value: "Task",
    bgColor: "#DF2F4A",
  },
  {
    id: 7,
    value: "",
    bgColor: "#C4C4C4",
  },
];

export const priorityColData = [
  {
    id: 1,
    value: "Critical",
    bgColor: "#216EDF",
  },
  {
    id: 2,
    value: "High",
    bgColor: "#FDAB3D",
  },
  {
    id: 3,
    value: "Medium",
    bgColor: "#A1E3F6",
  },
  {
    id: 4,
    value: "Low",
    bgColor: "#7F5347",
  },
  {
    id: 5,
    value: "Best Effort",
    bgColor: "#00C875",
  },
  {
    id: 6,
    value: "Missing",
    bgColor: "#DF2F4A",
  },
];

export const typeColData = [
  {
    id: 1,
    value: "Quality",
    bgColor: "#216EDF",
  },
  {
    id: 2,
    value: "Feature",
    bgColor: "#FDAB3D",
  },
  {
    id: 3,
    value: "Bug",
    bgColor: "#A1E3F6",
  },
  {
    id: 4,
    value: "Test",
    bgColor: "#7F5347",
  },
  {
    id: 5,
    value: "Security",
    bgColor: "#00C875",
  },
  {
    id: 6,
    value: "",
    bgColor: "#DF2F4A",
  },
];

export const tableRows = [
  {
    rowId: 1,
    taskValue: "Create monday UI",
    taskCheck: true,
    ownerValue: "",
    ownerCheck: true,
    statusValue: "",
    statusCheck: true,
    priorityValue: "",
    priorityCheck: true,
    typeValue: "",
    typeCheck: true,
    estimatedSPValue: "",
    etimatedSPCheck: true,
    actualSPValue: "",
    actualSPCheck: true,
    taskDueDateValue: "",
    taskDueDateCheck: false,
    roleValue: "",
    roleCheck: false,
    itemIdValue: "",
    itemIdCheck: false,
    rowCheck: false,
  },
];
