export const tableColumnsData = [
  {
    id: 1,
    colName: "Owner",
    styles: "",
    colStyle: "w-24",
    headingStyle: "",
    infoIcon: false,
    dottedIcon: true,
    sortable: true,
    checked: true,
  },
  {
    id: 2,
    colName: "Status",
    styles: "",
    colStyle: "w-36",
    headingStyle: "",
    infoIcon: false,
    dottedIcon: true,
    sortable: true,
    checked: true,
  },
  {
    id: 3,
    colName: "Priority",
    styles: "",
    colStyle: "w-36",
    headingStyle: "",
    infoIcon: false,
    dottedIcon: true,
    sortable: true,
    checked: true,
  },
  {
    id: 4,
    colName: "Type",
    styles: "",
    colStyle: "w-36",
    headingStyle: "",
    infoIcon: false,
    dottedIcon: true,
    sortable: true,
    checked: true,
  },
  {
    id: 5,
    colName: "Estimated SP",
    styles: "",
    colStyle: "w-36",
    headingStyle: "",
    infoIcon: true,
    dottedIcon: true,
    sortable: true,
    checked: true,
  },
  {
    id: 6,
    colName: "Actual SP",
    styles: "",
    colStyle: "w-36",
    headingStyle: "",
    infoIcon: true,
    dottedIcon: true,
    sortable: true,
    checked: true,
  },
  {
    id: 7,
    colName: "Task Due Date",
    styles: "",
    colStyle: "w-36",
    headingStyle: "",
    infoIcon: true,
    dottedIcon: true,
    sortable: true,
    checked: false,
  },
  {
    id: 8,
    colName: "Role",
    styles: "",
    colStyle: "w-36",
    headingStyle: "",
    infoIcon: true,
    dottedIcon: true,
    sortable: true,
    checked: false,
  },
  {
    id: 9,
    colName: "Item ID",
    styles: "",
    colStyle: "w-36",
    headingStyle: "",
    infoIcon: true,
    dottedIcon: true,
    sortable: true,
    checked: false,
  },
];

export const statusColData = [
  {
    id: 1,
    name: "Ready to Start",
    bgColor: "#216EDF",
  },
  {
    id: 2,
    name: "In Progress",
    bgColor: "#FDAB3D",
  },
  {
    id: 3,
    name: "Waiting for review",
    bgColor: "#A1E3F6",
  },
  {
    id: 4,
    name: "Pending Deploy",
    bgColor: "#7F5347",
  },
  {
    id: 5,
    name: "Done",
    bgColor: "#00C875",
  },
  {
    id: 6,
    name: "Task",
    bgColor: "#DF2F4A",
  },
  {
    id: 7,
    name: "",
    bgColor: "#C4C4C4",
  },
];

export const priorityColData = [
  {
    id: 1,
    name: "Critical",
    bgColor: "#216EDF",
  },
  {
    id: 2,
    name: "High",
    bgColor: "#FDAB3D",
  },
  {
    id: 3,
    name: "Medium",
    bgColor: "#A1E3F6",
  },
  {
    id: 4,
    name: "Low",
    bgColor: "#7F5347",
  },
  {
    id: 5,
    name: "Best Effort",
    bgColor: "#00C875",
  },
  {
    id: 6,
    name: "Missing",
    bgColor: "#DF2F4A",
  },
];

export const typeColData = [
  {
    id: 1,
    name: "Quality",
    bgColor: "#216EDF",
  },
  {
    id: 2,
    name: "Feature",
    bgColor: "#FDAB3D",
  },
  {
    id: 3,
    name: "Bug",
    bgColor: "#A1E3F6",
  },
  {
    id: 4,
    name: "Test",
    bgColor: "#7F5347",
  },
  {
    id: 5,
    name: "Security",
    bgColor: "#00C875",
  },
  {
    id: 6,
    name: "",
    bgColor: "#DF2F4A",
  },
];
