import Header from "./ui/Header/page";
import NavAside from "./ui/Sidebar/page";
import "./globals.css";

import {
  noto_sans_jp,
  noto_kufi_arabic,
  noto_sans_hebrew,
  roboto,
  figtree,
} from "./public/fonts/fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${noto_sans_jp.className} ${noto_kufi_arabic.className} ${noto_sans_hebrew.className} ${roboto.className} ${figtree.className} antialiased`}
      >
        <div className="min-h-screen">
          <Header />
          <div className="flex justify-between gap-3 h-[calc(100vh-48px)]">
            <aside className="sidebar bg-[#F7FBF8] w-64 rounded-tr-lg pt-1 pb-2 h-full text-primary">
              <NavAside />
            </aside>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
